### ISSUE TITLE
Contrtibution Help

### ISSUE THREAD

**Issue by LandonPatmore** [fluffy-mods/ModManager#106]
Looks like there are some things that I could help fix/optimize for you, however what is stopping me is actually compiling the mod.  I am looking to import the project, and it looks like there is a private repo you use for UI elements?

It looks to be located at: `..\..\..\TOOLS\FluffyUI\FluffyUI\FluffyUI.csproj` on your system.  Yet, when I look into your repositories, it is nowhere to be found.

I would enjoy contributing, just need help on this part.

**Comment by dpeter99** [comment]
I just decided to do the same (try and contribute) I think the FluffyUI is internal and not released publically. The compile dll is in the repo tho and with that i did managge to make it work.
I'm looking to add dragging to the main window, and maybe folders to better organize the mods. (A collapsable folder for Fluffys mods another for Stuff that does combat etc. So i won't ahave such a long mod list)

**Comment by LandonPatmore** [comment]
@dpeter99 Well that is unfortunate...appreciate you looking into it as well.  I'm not a C# guy.  Interesting as to why its open source if the "brunt" of the work is closed source.

**Comment by FluffierThanThou** [comment]
sorry folks, that was not intentional. 

It's available here now; https://github.com/fluffy-mods/FluffyUI

Please don't judge me. I've been wanting to make a common library dll for ages, but it never got off the ground. It's basically a bunch of disconnected helper functions that some of my mods use parts of.

**Comment by LandonPatmore** [comment]
@FluffierThanThou I'd like to apologize if that comment came off as "brash".  I appreciate you getting back and allowing some open source help on the project.
