### ISSUE TITLE
Can't mass subscribe to mods

### ISSUE THREAD

**Issue by Kongo77** [fluffy-mods/ModManager#167]
**Describe the bug**  
I can't get the mod to mass subscribe to missing mods.
From what I understand from the mod description this should be possible(?)
After importing a string with mods and loading that saved list, the mods that I have not subscribed to before are greyed out.
When clicking them nothing loads in the preview pane, and I can't locate any button to subscribe to the missing mod.
Please see screenshot.

**Expected behavior**  

As I've not used mod manager before I am not too sure, but I guess I should be offered to download the missing mod somewhere (?)

**Steps to reproduce**  

Start game with cleared mod list (only harmony, core, royalty, mod manager)
Load a mod list including both already subscribed mods and missing mods.
Click one of the non-subscribed mods.  

**Other mods**  
Loaded string: 
Version: 1
Name: western
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: automatic.startupimpact
  Name: Startup impact
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: fluffy.modmanager
  Name: Mod Manager

**Output log**  
Not sure if relevant as i have not started the game?

**Save game**  
Dont have one.

**Screenshots**  

**Environment**  
 - OS: Win 11
 - 32/64 bits  64
 
**Game**
 - 32/64 bits 64 bits
 - Steam/DRM free Steam
 - Version 1.3.3389
![screenshot](https://user-images.githubusercontent.com/39984637/173238879-bc1ec343-a07d-42ef-a14e-5508de27a63c.png)

**Comment by Unfaced85** [comment]
I have the same, wanted to load Quill18 Modlist 
http://quill18.com/mods/rimworld-western-2022-06-10.txt
load from string selected. Mod Manager says it created a list called "western" but that was it - I do not see the mods loaded / subscribing at all

**Comment by benjaminiserman** [comment]
+3, me and some friends are having this issue as well.

**Comment by TheEskir** [comment]
Tbh this makes perfect sense and the steam page claiming this is possible seems... outdated? Wrong?
The mod list, exported as String, only contains mod names and XML Package IDs found in the mod files. 
It's impossible to ascertain what workshop ID is behind these, as (to my knowledge) there is no API to search for said package IDs on the workshop (and there won't be, this would require the workshop search to actually go through the uploaded files). 

The exported mod list would have to contain the actual workshop page IDs for this to work.

**Comment by benjaminiserman** [comment]
Yup. I might try and fix this myself, since it seems this feature hasn't worked in 2 years.

**Comment by benjaminiserman** [comment]
I've also included a patched release, linked in the pull request.
