### ISSUE TITLE
bug in 1.30.869 - does not allow in-mod menus to populate. 

### ISSUE THREAD

**Issue by MrWashingToad** [fluffy-mods/ModManager#55]
v.1.30.869 does not allow the in-mod buttons at the bottom of mod to be clicked. Cannot load from string or from save - as the menus never pop up. Loading v.1.27.851 from GitHub enables this function.

**Comment by questionmarkexclamationpoint** [comment]
Same issue here.

**Comment by FluffierThanThou** [comment]
Yeah, I messed up window dragging. The widget is eating all the clicks, so other UI elements stopped responding. Steam release has been rolled back, will fix the problem tonight.

**Comment by FluffierThanThou** [comment]
ok, 'fixed' in the latest release.
