### ISSUE TITLE
Please add Russian translation

### ISSUE THREAD

**Issue by lex1975** [fluffy-mods/ModManager#61]
[Russian.zip](https://github.com/fluffy-mods/ModManager/files/3907897/Russian.zip)
Russian translation for Mod Manager v1.31.872 (1.0.2282)
I don’t know how to pull request, sorry.

**Comment by CandyFiend** [comment]
Надо форкнуть (ответвить) репозиторий к себе, чтобы у тебя на аккаунте была копия. Далее ты его (свой) клонируешь на компьютер, меняешь файлы, делаешь пул реквест на свою копию репозитория. Потом запрашиваешь слияние твоего репозитория (мастер ветка) и оригинального. Рекомендую программу github desktop, если не умеешь пользоваться git.
Я тоже сегодня переводил, потом увидел твой перевод, поправил явные ошибки в своём (они почти одинаковые) и запулил. Ждем ответ.

**Comment by FluffierThanThou** [comment]
thanks to both of you! I've merged CandyFiends' version (simply because that was easier), but given both of you credit. I hope that's okay?
