### ISSUE TITLE
"<mod>0.0.0 is expected. 0.0 is found"

### ISSUE THREAD

**Issue by Maykeye** [fluffy-mods/ModManager#74]
**Describe the bug**  
After installation opening ModManager I see errors like "Depends on Royalty v>=0.0.0, v0.0 is installed"
See, screenshot below

**Expected behavior**  
Not see them as (a) there were no errors in standard mod manager, (b) v0.0.0 and v0.0 is probably the same version(or lack of specified version) anyway

**Steps to reproduce**  
Open mod manager from the main menu

**Other mods**  
Royalty DLC, MegaCorp, 

Here's exported mod list (I had to rename it to .txt, as github doesn't let to upload xml)
[1.xml.txt](https://github.com/fluffy-mods/ModManager/files/4350100/1.xml.txt)

**Output log**  
[Log from Ctrl-F12](https://gist.github.com/d63e70021c5605e2fd0804ef76b0d794)

**Save game**  
N/A

**Screenshots**  
![image](https://user-images.githubusercontent.com/13607441/76982829-a5f37d00-6966-11ea-9a65-3aa9c21070e3.png)

**Environment**  
Windows 10, 64
 
**Game**
Steam 1.1.2575, 64-bit version, Royalty installed

**Comment by Maykeye** [comment]
Here is for comparison the same modlist but without modmanager:

![image](https://user-images.githubusercontent.com/13607441/76984051-85c4bd80-6968-11ea-979c-222fd5290854.png)

Default mod manager displays that MegaCorp depends on Royalty DLC, but there is no version mismatch

**Comment by AerosolNinja** [comment]
I am experiencing the same thing as Maykeye with strange dependency errors.

[Player.log](https://github.com/fluffy-mods/ModManager/files/4351075/Player.log)
[Player-prev.log](https://github.com/fluffy-mods/ModManager/files/4351076/Player-prev.log)

**Comment by FluffierThanThou** [comment]
thank you, will have a look now

**Comment by FluffierThanThou** [comment]
Should be fixed now, thanks for reporting!
