### ISSUE TITLE
Incorrect Dependency Issues

### ISSUE THREAD

**Issue by AerosolNinja** [fluffy-mods/ModManager#75]
**Describe the bug**  

Mod manager lists strange missing dependencies that don't actually exist.  Just creates a nag screen.

**Expected behavior**  

Nothing!  These mods don't have or aren't lacking dependencies.

**Steps to reproduce**  

1. Open mod manager with my modlist.
2. See issues.

**Other mods**  

Lots, but I do not get any log errors.

**Output log**  

[Player.log](https://github.com/fluffy-mods/ModManager/files/4352125/Player.log)
[Player-prev.log](https://github.com/fluffy-mods/ModManager/files/4352126/Player-prev.log)
[output_log.txt](https://gist.github.com/HugsLibRecordKeeper/15deac0a749d80e0e74d2c8296517807)

**Save game**  

Haven't played yet.

**Screenshots**  

![Fluffy](https://user-images.githubusercontent.com/55816747/77020662-c0672f80-6941-11ea-8cdd-9016c435ab3a.png)

**Environment**  
 - OS:  Windows 10
 - 64 Bit
 
**Game**
 - 64 bits
 - Steam
 - 1.1.2575

Thank you!  <3

**Comment by FluffierThanThou** [comment]
incompatibilities were incorrectly being shown as dependencies, should have been fixed.
