### ISSUE TITLE
Adding mods to mod list is laggy

### ISSUE THREAD

**Issue by EnderShadow** [fluffy-mods/ModManager#76]
**Describe the bug**  
After starting the game with a minimal mods list (Harmony, Core, and Mod Manager), after adding a few 10's of mods to list dragging and dropping mods to/from the active list slows down to an unusable speed. It also affects scrolling when dragging the scroll bar, but not using the scroll wheel.

**Expected behavior**  
No slowdown when adding mods to the list of active mods.

**Steps to reproduce**  
1. Create a mod list with around 60 mods from in-game by dragging and dropping mods into the active mods list
2. The game will slow down as you drag them once you get near 60.

**Other mods**  
The mod list I was using where this appears is [here](https://github.com/fluffy-mods/ModManager/files/4366343/Partial.1.1.2.txt). While this seems similar to #70, removing JecsTools from the list does not change anything.

**Environment**  
 - OS: Manjaro Linux
 - 64 bits
 
**Game**
 - 64 bits
 - Steam
 - 1.1.2579

**Comment by EnderShadow** [comment]
What?

**Comment by FluffierThanThou** [comment]
This should have been fixed with yesterday's update.
