### ISSUE TITLE
auto sort  button doesnt work

### ISSUE THREAD

**Issue by Mtg202** [fluffy-mods/ModManager#84]
**Describe the bug**  
i clicked on the auto sort button and it opened the debug page with a bug that is listed in the log

**Expected behavior**  
for the mod manager to auto sort the mods

**Steps to reproduce**  

1.open rimworld with mod manger
2.click auto-sort
3.look cofused and the lack of sorting :(

**Other mods**  
it was on the main menu of the mod manager in rim world. 
im running 400 other mods but non of them should have affected the mod manager 

**Output log**  
https://gist.github.com/a4917b82923549d2636921d30eeb35e1

**Save game**  
N/A i was in the mod manager not the game

**Screenshots**  
N/A nothing looks off in the UI

**Environment**  
 - windows 10
 -64 bit
 
**Game**
rimworld

just wanted to say, i love your work and if nothing else you made my world a happier place with all the work you do.

**Comment by FluffierThanThou** [comment]
I'll have a look, thanks!
