### ISSUE TITLE
Pressing "Show Settings" in Mod Settings resets Mod Manager preferences/colors

### ISSUE THREAD

**Issue by HereShoo** [fluffy-mods/ModManager#86]
**Describe the bug**  

The debug log triggered after checking Mod Manager's settings from "Mod Settings" inside "Options." Then, all settings and mod colors saved by Mod Manager had reverted to default values (all mods are white again). It doesn't happen when "Mods" in the main menu had been opened prior, only when going straight Options > Mod Settings > Mod Manager's Show Settings after freshly loading the game. It also doesn't happen when I haven't changed any mod's color yet.

**Expected behavior**  

All my 250 mods retain the colors I assigned them through my unhealthy display of OCD.

**Steps to reproduce**  

1. Color a mod and then quit to OS, and start the game up again.
2. Right after freshly loading the game (not clicking "Mods" first since doing that prevents the problem somehow), go to "Options"
3. Go to "Mod Settings"
4. Go to Mod Manager's "Show Settings," where it should trigger the debug log error.

**Other mods**  

Even running just Core, Royalty, Harmony, HugsLib, and Mod Manager lets me reproduce the error on my end.

**Output log**  
 
[Log](https://gist.github.com/HugsLibRecordKeeper/b72e73c0079a341e7cd5630f076e2ef4)

**Save game**  

**Screenshots**  

**Environment**  
 - OS: Windows 10
 - 32/64 bits 64 bit
 
**Game**
Rimworld
 - 64 bit
 - Steam
 - Version 1.1

Thanks for all the work you do. Arranging all my mods properly into categories would be a real pain if it wasn't for the features from this mod!

**Comment by FluffierThanThou** [comment]
thanks for the report, should be fixed with the 1.2 release
