### ISSUE TITLE
"Exception in custom XML loader for ModManager.incompatible"

### ISSUE THREAD

**Issue by HereShoo** [fluffy-mods/ModManager#87]
**Describe the bug**  

The debug log pops up with some errors when opening up "Mods." It doesn't do anything wonky though, I think. I don't know when this started, as I've only just used dev mode recently.

**Expected behavior**  

Nothing should happen.

**Steps to reproduce**  

1. With debug mode on, open up "Mods"
2. The debug log should pop up.

**Other mods**  

[Mod List Link](https://gist.github.com/Maconnais/0c5ee5757e01414baac70a21b2fc6e9d)
I have 250+ mods, though this happens even when most mods except Harmony, Core, Royalty, HugsLib and Mod Manager are inactive. In the screenshot it seems Change Dresser and Prepare Carefully are in the red, however I've unsubbed to both and this still happens.

**Output log**  

[Log Link](https://gist.github.com/HugsLibRecordKeeper/e642f111402ab118ce8824d3365dbff3)

**Save game**  

**Screenshots**  

![](https://user-images.githubusercontent.com/64010410/79762330-356cc100-8355-11ea-9e39-69c7086536e8.png)

**Environment**  
 - OS: Windows 10
 - 32/64 bits 64 bit
 
**Game**
Rimworld
 - 64 bits
 - Steam
 - Version 1.1

**Comment by FluffierThanThou** [comment]
does this problem still occur?

**Comment by VilcsiTH** [comment]
This problem still occurs. The mod that resulted in this error was "Retextured Interaction Spots Project"(steam ID 2121663243) for me, and the error was `"Exception in custom XML loader for ModManager.Incompatible. Node is: <li>Better Spots<li>".`
Nothing was active besides Mod Manager, HugsLib, Harmony, BetterLoading and the official DLCs.
I had Better Spots subbed and installed when this error first came up, so I thought that the existence of the mod was the issue, but after unsubbing and removing, the error persisted. The line responsible for the error can be found in Retextured Interaction Spots Project's About folder, inside Manifest.xml.
