### ISSUE TITLE
Debugging with VS

### ISSUE THREAD

**Issue by mohas** [fluffy-mods/ModManager#90]
Hi, I didn't know anywhere else to reach you can your mods be debugged with VS? can you point me to the right direction?

**Comment by FluffierThanThou** [comment]
I have yet to figure out how to do this. Theoretically, it is possible, but
you need a custom build version of the unity assemblies. Brainzz has got it
figured out, might be worth asking him on discord.

**Comment by mohas** [comment]
OK thanks
