### ISSUE TITLE
breaking mods

### ISSUE THREAD

**Issue by FluffierThanThou** [fluffy-mods/ModManager#92]
Reported by: Tyrant
Description:
The following mods break Mod Manager just from being subscribed to, they don't have to be enabled:
<br>Pawnmorpher:  <a class="bb_link" href="https://steamcommunity.com/workshop/filedetails/?id=1786466855" target="_blank" rel="noreferrer">https://steamcommunity.com/workshop/filedetails/?id=1786466855</a> <br>Kurin HAR Edition:  <a class="bb_link" href="https://steamcommunity.com/workshop/filedetails/?id=2055185860" target="_blank" rel="noreferrer">https://steamcommunity.com/workshop/filedetails/?id=2055185860</a> <br>Prepare Moderately:  <a class="bb_link" href="https://steamcommunity.com/workshop/filedetails/?id=2057362949" target="_blank" rel="noreferrer">https://steamcommunity.com/workshop/filedetails/?id=2057362949</a> <br>Kurin(Garam) Boots And Glove Fix:  <a class="bb_link" href="https://steamcommunity.com/workshop/filedetails/?id=2076676300" target="_blank" rel="noreferrer">https://steamcommunity.com/workshop/filedetails/?id=2076676300</a> <br><br>In case any of these mods update in the meantime and leave you unable to replicate the errors, here's a backup of them:  <a class="bb_link" href="https://steamcommunity.com/linkfilter/?url=https://files.catbox.moe/1cyfvn.rar" target="_blank" rel="noreferrer">https://files.catbox.moe/1cyfvn.rar</a>

**Comment by Tachyonite** [comment]
Mod of PM here, this is an issue with the manifest not being read as the mod name, but requires the package ID which is not currently in use. I'm pushing an update soon to fix this on our end, but Mod Manager might still need a 'fallback' to find a mod with the name rather than package ID in case people are still using it.

**Comment by FluffierThanThou** [comment]
This is probably too little, too late, but for the record, these are all user errors on the part of the modders;

Prepare Moderately was adding dependcy information in the About.xml format to Manifest.xml.
Pawnmorpher and Kurin(Garam)... where using incorrect mod identifiers (adding spaces and other text).
Kurin HAR edition has a reference to the `html` rather than the `raw` version on the online manifest.
