### ISSUE TITLE
Bug report on "defines the same field twice: version."

### ISSUE THREAD

**Issue by Genaeve** [fluffy-mods/ModManager#98]
**Describe the bug**  
Debug log pops up with this particular part in red. This is more of a nuisance, I can still play, 

**Expected behavior**  
I don't expect it to cause the debug log to popup

**Steps to reproduce**  
Everytime I start up with ModManager installed. 
1. I even disabled every mod except Modmanager, Harmony, and Hugslib
2.
3.

**Other mods**  
When it first happened, yes, and even with all other mods (except Harmony & Hugslib, although it refences Jec's)

**Output log**  
<script src="https://gist.github.com/Genaeve/0e464f6f1dded843f63735d2a716e955.js"></script>

**Save game**  
It's not part of a saved game, it does this no matter what. Just let me know if you need one, as I'll have to start one with no mods. 

**Screenshots**  
No screenshots

**Environment**  
 - OS: <Windows 10>
 - 64 bits 
 
**Game**
 Steam Rimworld 1.1

**Comment by Genaeve** [comment]
For "Other Mods" I wrote: 
Other mods
When it first happened, yes, and even with all other mods (except Harmony & Hugslib, although it refences Jec's)
What I meant, 
Other mods
When it first happened, yes, and even with all other mods **_disabled_**. (except Harmony & Hugslib, although it refences Jec's)

**Comment by FluffierThanThou** [comment]
this is working as intended
